# ======================================================
#  vxLinker - Minecraft ↔ Discord Hesap Eşleştirme Sistemi
#  Geliştirici: Velvexa
# ======================================================

# ======================================================
#  DİL AYARI
# ------------------------------------------------------
#  Plugin mesajlarının hangi dil dosyasından yükleneceğini belirler.
#  Örnekler:
#    - TR → messages_TR.yml
#    - EN → messages_EN.yml
# ======================================================
language: TR

  # ======================================================
  #  AKILLI YENİDEN DOĞRULAMA (Re-Verify System)
  # ------------------------------------------------------
  #  Discord bağlantılarını düzenli aralıklarla kontrol eder.
  #  Eğer oyuncu Discord sunucusunda değilse veya doğrulama rolünü kaybetmişse,
  #  belirlenen aksiyona göre işlem yapar.
  # ------------------------------------------------------
  #  enabled: true/false → sistemi aktif eder veya devre dışı bırakır.
  #  interval-hours: kontrol aralığı (saat cinsinden)
  #  action: "unlink" → bağlantıyı otomatik kaldırır.
  #           "notify" → yalnızca uyarı log’u oluşturur.
  #  log-channel-id: Discord log kanalının ID’si (boş bırakılırsa mesaj gönderilmez)
  # ======================================================
reverify:
    enabled: true
    interval-hours: 6
    action: "notify"
    log-channel-id: ""

link:
  # Oyuncuya verilecek eşleşme kodunun uzunluğu
  code-length: 6

  # Kodun saniye cinsinden geçerlilik süresi (varsayılan: 300 = 5 dakika)
  expire-seconds: 300




# ======================================================
#  DISCORD BOT AYARLARI
# ======================================================
discord:
  enabled: true

  # Bot tokeninizi buraya girin
  bot-token: "BOT_TOKEN"

  # Botun aktif olacağı Discord sunucusunun ID’si
  guild-id: "123456"

  # Minecraft hesabını başarıyla eşleştirenlere verilecek rolün ID’si
  role-id-verified: "123456"

  # Bot durum metni (örnek: “Minecraft - Discord Eşleme Aktif”)
  status: "Minecraft - Discord Eşleme Aktif"


# ======================================================
#  VERİ DEPOLAMA (YAML / SQLITE / MYSQL)
# ------------------------------------------------------
#  type: Depolama türü
#   - YAML   → Basit dosya temelli sistem
#   - SQLITE → Otomatik yerel veritabanı (vxlinker.db)
#   - MYSQL  → Uzaktan MySQL sunucusu bağlantısı
# ======================================================
storage:
  type: "SQLITE"

  # ------------------------------------------------------
  # MYSQL AYARLARI
  # ------------------------------------------------------
  mysql:
    host: ""
    port: 3306
    database: ""
    username: ""
    password: ""

  # Son kullanılan depolama türü (otomatik yönetilir)
  last-storage: "SQLITE"


# ======================================================
#  ÖDÜL SİSTEMİ (RewardManager)
# ------------------------------------------------------
#  - İlk eşleşme ödülü: Oyuncu hesabını ilk kez bağladığında verilir.
#  - Periyodik ödül: Discord bağlantısı aktif oyunculara belirli aralıklarla verilir.
#  - Komutlarda {player} değişkeni oyuncu ismiyle değiştirilir.
#  - Süre biçimleri: 10m (dakika), 1h (saat), 1d (gün)
# ======================================================
rewards:
  first-link:
    enabled: true
    message: "&aTebrikler! Discord hesabını başarıyla eşleştirdin ve ödül kazandın!"
    commands:
      - "lp user {player} parent addtemp vip 7d"
    items:
      - "DIAMOND:3"
      - { material: "GOLD_INGOT", amount: 8, name: "&6Altın Hediye" }

  interval:
    enabled: true
    every: "1h"   # 10m / 1h / 1d
    message: "&aDiscord bağlantın aktif olduğu için 1000 coin kazandın!"
    commands:
      - "eco give {player} 1000"
    items: []


# ======================================================
#  ÖDÜL LOG SİSTEMİ 
# ------------------------------------------------------
#  - Oyuncuların aldığı tüm ödüller ayrı bir log dosyasında veya veritabanında saklanır.
#  - type:
#      - YAML   → reward-logs.yml
#      - SQLITE → reward-logs.db
#      - MYSQL  → MySQL içindeki reward_logs tablosu
# ======================================================
reward-logs:
  enabled: true
  type: "SQLITE"

  # MYSQL için özel tablo ismi
  mysql-table: "reward_logs"


# ======================================================
#  NOTLAR
# ------------------------------------------------------
#  YAML: Veriler "linked-accounts.yml" ve "reward-logs.yml" dosyalarında tutulur.
#  SQLITE: Veriler "vxlinker.db" içinde saklanır.
#  MYSQL: Veriler uzaktaki MySQL sunucusuna yazılır.
#  /vxlinkerreload komutu ile tüm ayarlar, mesajlar ve ödül sistemi anında yeniden yüklenir.
# ======================================================
